### ISSUE TITLE
Setup a fork on Gnosis Safe for production usage

### ISSUE THREAD

**Issue by troggy** [leapdao/leap-safe#3]
# Bounty

## Scope

- fork Gnosis Safe and setup a basic bounty process for it (labels, bounty.md and PR templates)
- obtain an API key from Blocknative.com (required by Gnosis Safe mainnet)
- create an S3 website + CloudFront distribution (with SSL) + Route53 record
- create production build and upload to S3 bucket

## Deliverables

- Safe up and running at safe.leapdao.org

## Funding Circle

General Circle

## Bounty Owner/Gardener

@troggy as **Process Engineer**

## Gain for the Role

Running our own Safe fork in production

## Roles
bounty gardener: @troggy / 30 DAI 
bounty worker: @troggy / 70%
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by troggy** [comment]
Delivered:
- CloudFront distribution with SSL *.leapdao.org
- Route53 record for safe.leapdao.org
- S3 bucket serving static website
- Blocknative API key (updated leapdao-dev.kdbx KeepPass file)
- deployment scripts and instruction
- updated UI

**Comment by johba37** [comment]
- [x] reviewed cloudfront
- [x] reviewed s3
- [x] checked blocknative key in keypass file
- [x] glanced over deployment script and got familiar with wallet
